create table if not exists public.user_roles (
  id integer generated by default as identity primary key,
  email text not null unique,
  role text not null default 'member',
  display_name text,
  created_at text not null default to_char(current_timestamp at time zone 'UTC', 'YYYY-MM-DD HH24:MI:SS')
);

create table if not exists public.content_items (
  id integer generated by default as identity primary key,
  section text not null,
  key text not null,
  value text not null default '',
  updated_at text not null default to_char(current_timestamp at time zone 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
  constraint content_section_key_unique unique (section, key)
);

create table if not exists public.programs (
  id integer generated by default as identity primary key,
  name text not null,
  day text not null,
  time text not null,
  location text not null,
  description text not null default '',
  published boolean not null default false
);

create table if not exists public.cells (
  id integer generated by default as identity primary key,
  name text not null,
  leader text not null,
  neighborhood text not null,
  city text not null,
  day text not null,
  time text not null,
  age_range text,
  audience text,
  published boolean not null default false
);

create table if not exists public.courses (
  id integer generated by default as identity primary key,
  slug text not null unique,
  name text not null,
  description text not null default '',
  teacher text,
  workload text,
  audience text,
  start_date text,
  modality text,
  enrollment_status text not null default 'closed',
  certificate_enabled boolean not null default false,
  published boolean not null default false
);

create table if not exists public.course_modules (
  id integer generated by default as identity primary key,
  course_id integer not null references public.courses(id),
  title text not null,
  position integer not null default 0
);

create table if not exists public.lessons (
  id integer generated by default as identity primary key,
  module_id integer not null references public.course_modules(id),
  title text not null,
  content text not null default '',
  video_url text,
  material_url text,
  position integer not null default 0
);

create table if not exists public.course_progress (
  id integer generated by default as identity primary key,
  email text not null,
  course_id integer not null references public.courses(id),
  lesson_id integer not null references public.lessons(id),
  completed_at text not null default to_char(current_timestamp at time zone 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
  constraint progress_user_lesson_unique unique (email, lesson_id)
);

create table if not exists public.events (
  id integer generated by default as identity primary key,
  name text not null,
  description text not null default '',
  event_date text not null,
  time text not null,
  location text not null,
  capacity integer,
  registration_status text not null default 'closed',
  published boolean not null default false,
  image_url text
);

create table if not exists public.galleries (
  id integer generated by default as identity primary key,
  name text not null,
  category text not null,
  event_date text,
  published boolean not null default false
);

create table if not exists public.ministries (
  id integer generated by default as identity primary key,
  name text not null,
  description text not null default '',
  leader text,
  schedule text,
  image_url text,
  published boolean not null default false
);

create table if not exists public.gallery_photos (
  id integer generated by default as identity primary key,
  gallery_id integer not null references public.galleries(id),
  image_url text not null,
  alt_text text not null default '',
  position integer not null default 0
);

create table if not exists public.media_assets (
  key text primary key,
  content_type text not null,
  size integer not null,
  created_by text not null,
  created_at text not null default to_char(current_timestamp at time zone 'UTC', 'YYYY-MM-DD HH24:MI:SS')
);

create table if not exists public.admin_credentials (
  id integer primary key,
  email text not null unique,
  password_hash text not null,
  created_at text not null default to_char(current_timestamp at time zone 'UTC', 'YYYY-MM-DD HH24:MI:SS')
);

create table if not exists public.admin_sessions (
  token_hash text primary key,
  admin_id integer not null references public.admin_credentials(id),
  expires_at bigint not null
);

create table if not exists public.admin_login_attempts (
  key text primary key,
  attempts integer not null,
  reset_at bigint not null
);

create table if not exists public.submissions (
  id integer generated by default as identity primary key,
  kind text not null,
  payload text not null,
  status text not null default 'novo',
  owner_email text,
  event_id integer references public.events(id),
  registrant_email text,
  created_at text not null default to_char(current_timestamp at time zone 'UTC', 'YYYY-MM-DD HH24:MI:SS')
);

create unique index if not exists submission_event_email_idx
  on public.submissions (event_id, registrant_email)
  where event_id is not null and registrant_email is not null and status <> 'cancelado';

create index if not exists submissions_event_status_idx on public.submissions (event_id, status);
create index if not exists submissions_created_at_idx on public.submissions (created_at desc);
create index if not exists events_public_date_idx on public.events (published, event_date desc, id desc);
create index if not exists galleries_public_date_idx on public.galleries (published, event_date desc, id desc);
create index if not exists gallery_photos_gallery_position_idx on public.gallery_photos (gallery_id, position, id);
create index if not exists course_modules_course_position_idx on public.course_modules (course_id, position, id);
create index if not exists lessons_module_position_idx on public.lessons (module_id, position, id);
create index if not exists admin_sessions_admin_id_idx on public.admin_sessions (admin_id);
create index if not exists course_progress_course_id_idx on public.course_progress (course_id);
create index if not exists course_progress_lesson_id_idx on public.course_progress (lesson_id);

do $$
declare
  table_name text;
begin
  foreach table_name in array array[
    'user_roles','content_items','programs','cells','courses','course_modules',
    'lessons','course_progress','events','galleries','ministries','gallery_photos',
    'submissions','media_assets','admin_credentials','admin_sessions','admin_login_attempts'
  ] loop
    execute format('alter table public.%I enable row level security', table_name);
    execute format('revoke all on table public.%I from anon, authenticated', table_name);
  end loop;
end $$;
