-- Rifa solidária (iPhone 17) para a compra do telão da igreja.
-- Cada pedido recebe números aleatórios de 00000 a 99999, reservados até o
-- pagamento por Pix ser confirmado no painel. Pedidos pendentes além do prazo
-- expiram e liberam os números; confirmar um pedido expirado gera números novos.

create table if not exists public.raffle_orders (
  id integer generated by default as identity primary key,
  code text not null unique,
  name text not null,
  email text not null,
  whatsapp text not null,
  quantity integer not null check (quantity between 1 and 1000),
  amount_cents integer not null check (amount_cents > 0),
  status text not null default 'pendente' check (status in ('pendente', 'pago', 'cancelado', 'expirado')),
  created_at timestamptz not null default now(),
  paid_at timestamptz
);

create table if not exists public.raffle_numbers (
  number integer primary key check (number between 0 and 99999),
  order_id integer not null references public.raffle_orders(id) on delete cascade
);

create index if not exists raffle_numbers_order_idx on public.raffle_numbers (order_id);
create index if not exists raffle_orders_status_created_idx on public.raffle_orders (status, created_at);
create index if not exists raffle_orders_created_idx on public.raffle_orders (created_at desc);

alter table public.raffle_orders enable row level security;
alter table public.raffle_numbers enable row level security;
revoke all on table public.raffle_orders from anon, authenticated;
revoke all on table public.raffle_numbers from anon, authenticated;
create policy raffle_orders_service_role_policy on public.raffle_orders for all to service_role using (true) with check (true);
create policy raffle_numbers_service_role_policy on public.raffle_numbers for all to service_role using (true) with check (true);

-- Sorteia números livres para o pedido. A chave primária impede que dois
-- pedidos simultâneos fiquem com o mesmo número.
create or replace function public.raffle_allocate_numbers(p_order_id integer, p_quantity integer)
returns integer
language plpgsql
volatile
security invoker
set search_path = public
as $$
declare
  missing integer := p_quantity;
  inserted integer;
  attempts integer := 0;
begin
  if (select count(*) from public.raffle_numbers) + p_quantity > 100000 then
    raise exception 'raffle_sold_out' using errcode = 'P0001';
  end if;
  while missing > 0 loop
    attempts := attempts + 1;
    if attempts > 200 then raise exception 'raffle_sold_out' using errcode = 'P0001'; end if;
    insert into public.raffle_numbers (number, order_id)
    select candidate, p_order_id
    from (
      select distinct floor(random() * 100000)::integer as candidate
      from generate_series(1, missing + 16)
    ) picks
    where not exists (select 1 from public.raffle_numbers taken where taken.number = picks.candidate)
    limit missing
    on conflict (number) do nothing;
    get diagnostics inserted = row_count;
    missing := missing - inserted;
  end loop;
  return p_quantity;
end;
$$;

create or replace function public.raffle_expire_pending(p_expire_hours integer)
returns integer
language plpgsql
volatile
security invoker
set search_path = public
as $$
declare
  expired integer;
begin
  with stale as (
    update public.raffle_orders
    set status = 'expirado'
    where status = 'pendente' and created_at < now() - make_interval(hours => greatest(p_expire_hours, 1))
    returning id
  )
  delete from public.raffle_numbers where order_id in (select id from stale);
  get diagnostics expired = row_count;
  return expired;
end;
$$;

create or replace function public.create_raffle_order(
  p_code text,
  p_name text,
  p_email text,
  p_whatsapp text,
  p_quantity integer,
  p_amount_cents integer,
  p_expire_hours integer
)
returns integer
language plpgsql
volatile
security invoker
set search_path = public
as $$
declare
  new_id integer;
begin
  perform public.raffle_expire_pending(p_expire_hours);
  insert into public.raffle_orders (code, name, email, whatsapp, quantity, amount_cents)
  values (p_code, p_name, p_email, p_whatsapp, p_quantity, p_amount_cents)
  returning id into new_id;
  perform public.raffle_allocate_numbers(new_id, p_quantity);
  return new_id;
end;
$$;

create or replace function public.set_raffle_order_status(p_order_id integer, p_status text)
returns integer
language plpgsql
volatile
security invoker
set search_path = public
as $$
declare
  order_row public.raffle_orders%rowtype;
  held integer;
begin
  if p_status not in ('pendente', 'pago', 'cancelado') then return 0; end if;
  select * into order_row from public.raffle_orders where id = p_order_id for update;
  if not found then return 0; end if;

  if p_status = 'cancelado' then
    delete from public.raffle_numbers where order_id = p_order_id;
  else
    select count(*)::integer into held from public.raffle_numbers where order_id = p_order_id;
    if held < order_row.quantity then
      perform public.raffle_allocate_numbers(p_order_id, order_row.quantity - held);
    end if;
  end if;

  update public.raffle_orders
  set status = p_status,
      paid_at = case when p_status = 'pago' then coalesce(order_row.paid_at, now()) else null end,
      -- Um pedido reaberto como pendente ganha um novo prazo de pagamento.
      created_at = case when p_status = 'pendente' and order_row.status <> 'pendente' then now() else order_row.created_at end
  where id = p_order_id;
  return 1;
end;
$$;

-- Número vencedor: o 1º prêmio da Loteria Federal; se ele não foi vendido,
-- vale o próximo número pago acima dele, voltando ao 00000 depois do 99999.
create or replace function public.raffle_winner(p_result integer)
returns table (number integer, order_id integer)
language sql
stable
security invoker
set search_path = public
as $$
  select n.number, n.order_id
  from public.raffle_numbers n
  join public.raffle_orders o on o.id = n.order_id and o.status = 'pago'
  order by (n.number < p_result), n.number
  limit 1;
$$;

revoke all on function public.raffle_allocate_numbers(integer, integer) from public, anon, authenticated;
revoke all on function public.raffle_expire_pending(integer) from public, anon, authenticated;
revoke all on function public.create_raffle_order(text, text, text, text, integer, integer, integer) from public, anon, authenticated;
revoke all on function public.set_raffle_order_status(integer, text) from public, anon, authenticated;
revoke all on function public.raffle_winner(integer) from public, anon, authenticated;
grant execute on function public.raffle_allocate_numbers(integer, integer) to service_role;
grant execute on function public.raffle_expire_pending(integer) to service_role;
grant execute on function public.create_raffle_order(text, text, text, text, integer, integer, integer) to service_role;
grant execute on function public.set_raffle_order_status(integer, text) to service_role;
grant execute on function public.raffle_winner(integer) to service_role;
